[package]
name = "husk-proc"
version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
description = "Procedural macros for the 'husk' crate"

[lib]
proc-macro = true

[dependencies]
quote.workspace = true
syn.workspace = true
